### ISSUE TITLE
support passing `env` with configure hook payload

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/nanobox-hooks-unfs#12]
Would it be possible for UNFS(and other data components) to support passing environment variables to the configure hook the same way the code configure hook does? https://github.com/nanobox-io/nanobox-hooks-code/blob/master/src/configure#L46-L64

@danhunsaker is writing an article on backups and wants to store things in the warehouse component. So from a data component, like UNFS, he needs evars available with connection info for platform components. I've already updated Odin to send the evars, if the configure hooks can now just handle them and set them in the container.

**Comment by tylerflint** [comment]
This shouldn't be a problem.

@notxarb thoughts?

**Comment by notxarb** [comment]
Yes, I think this should be possible, and I don't think it should cause any issues.
